ServiceHost = "0.0.0.0"
ServicePort = 8080
Token = "a157b23c"

[minio]
Endpoint = "localhost:9000"
BucketName = "images"

[jwt]
Token = "peppa"
ExpiresIn = "24h"

[Redis]
DialTimeout = "10s"
ReadTimeout = "10s"
